pipeline {
    agent none

    stages {

        stage('Git Pull Resources') {
            steps {
                checkout([$class: 'GitSCM', branches: [[name: '*/master']], doGenerateSubmoduleConfigurations: false, extensions: [], submoduleCfg: [], userRemoteConfigs: [[url: 'https://github.com/vagnerd/burnbag.git']]])
            }
        }

    }

}
