FROM metasploitframework/metasploit-framework
MAINTAINER Vagnerd Fernandes "vagner.rodrigues@gmail.com"

RUN apk add --no-cache git

RUN git clone https://github.com/vagnerd/burnbag.git /burnbag

ENTRYPOINT []
