pipeline {
    agent none

    stages {
        stage('Run SQLMap Pentest') {
            when {
                expression { params.url_hack }
            }
            
            agent {
                docker { image 'vagnerd/sqlmap:latest-jenkins' }
            }
            
            steps {
                sh "python /sqlmap/sqlmap.py --batch -u ${params.url_hack}"
            }
            
        }
    }
}
